spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8084/
  cloud.gateway:
    discovery:
      locator:
        enabled: false
        lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


server:
  port: 8080